---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nmthanh31/frontend:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000 # ⚠ targetPort phải khớp với containerPort
  type: LoadBalancer
  loadBalancerIP: 192.168.182.241 # ⚠ IP này phải thuộc dải MetalLB bạn đã cấu hình
