---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nmthanh31/frontend:latest # Thay bằng image của bạn
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Port ứng dụng frontend (React/Vite)
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80 # Port người dùng truy cập
      targetPort: 80 # Port trong container
  type: LoadBalancer # Nhờ MetalLB cấp IP nội bộ để truy cập
