---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc 
provisioner: kubernetes.io/no-provisioner 
volumeBindingMode: WaitForFirstConsumer 
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany 
  nfs:
    server: 192.168.182.130
    path: /data/user-service
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nmthanh31/user-service:__IMAGE_TAG__
          imagePullPolicy: Always 
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: user-data-volume
              mountPath: /app/data 
      volumes:
        - name: user-data-volume
          persistentVolumeClaim:
            claimName: user-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer #
