name: Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies & run unit tests
        working-directory: ./frontend
        run: |
          npm ci
          npm test -- --watchAll=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, scan and push frontend
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/frontend
          docker build --no-cache -t $IMAGE ./frontend
          trivy image --severity CRITICAL,HIGH --exit-code 1 --ignore-unfixed $IMAGE
          docker push $IMAGE

      - name: Decode kubeconfig
        run: echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $KUBECONFIG

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k3s/frontend/frontend-deployment.yaml
          kubectl rollout status deployment/frontend

      - name: Clean up kubeconfig
        if: always()
        run: rm -f $KUBECONFIG
