name: payment-service CI/CD

on:
  push:
    paths:
      - "backend/payment-service/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies & run unit tests
        working-directory: ./backend/payment-service
        run: |
          npm ci
          npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, scan and push payment-service
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.sha }}
          docker build -t $IMAGE ./backend/payment-service
          trivy image --skip-db-update --severity CRITICAL,HIGH --exit-code 0 --ignore-unfixed $IMAGE
          docker push $IMAGE

      - name: Inject image tag into Kubernetes YAML
        run: |  
          sed -i "s|__IMAGE_TAG__|${{ github.sha }}|g" k3s/payment/payment-deployment.yaml

      - name: Decode kubeconfig
        run: echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $KUBECONFIG

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k3s/payment/payment-deployment.yaml
          kubectl rollout status deployment/payment-service

      - name: Clean up kubeconfig
        if: always()
        run: rm -f $KUBECONFIG
